### model
model_name_or_path: memevis/supp4
#deepspeed: ds_z3_offload_config.json

### method
stage: sft_next_token
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 16
lora_alpha: 16
lora_dropout: 0.05




### dataset
dataset: train_1_4_6
template: qwen
cutoff_len: 2024
overwrite_cache: true
#overwrite_cache: false
preprocessing_num_workers: 256

### output
output_dir: adapters/memevis-supp4
logging_steps: 100
save_steps: 5000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 2
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 1000000